// src/users/entity/Passkey.entity.ts

import { Entity, PrimaryGeneratedColumn, Column, ManyToOne } from 'typeorm';
import { User } from 'src/users/entity/User.entity';

@Entity('Passkeys')
export class Passkey {
  @PrimaryGeneratedColumn()
  id: number; // Unique primary key for the database record

  @Column({ unique: true })
  credentialId: string; // The unique ID returned by the user's device (stored as base64url)

  @Column({ type: 'bytea' })
  publicKey: Buffer; // The public key generated by the device, stored as binary data

  @Column({ default: 0 })
  counter: number; // Security counter to prevent cloned authenticator replays

  @ManyToOne(() => User, (user) => user.id, { onDelete: 'CASCADE' })
  user: User; // Many passkeys belong to one user
}
